### ISSUE TITLE
fast and furious hobbs and shaw hdr10+ metadata

### ISSUE THREAD

**Issue by hyllm** [quietvoid/hdr10plus_parser#10]
metadata extracted can't be used... even HDR10 is not signaled when using HDR10+ metadata. other hdr10+ movies are OK

source:

> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format profile                           : Main 10@L5.1@High
> HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
> Width                                    : 3 840 pixels
> Height                                   : 2 160 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 23.976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
> Maximum Content Light Level              : 1000 cd/m2
> Maximum Frame-Average Light Level        : 419 cd/m2

encoded with x265

> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format profile                           : Main 10@L5.1@High
> HDR format                               : SMPTE ST 2094 App 4, Version 1
> Width                                    : 3 840 pixels
> Height                                   : 2 160 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 23.976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
> Maximum Content Light Level              : 1000 cd/m2
> Maximum Frame-Average Light Level        : 419 cd/m2

**Comment by quietvoid** [comment]
It says `HDR format : SMPTE ST 2094 App 4, Version 1`. That is HDR10+.
HDR10 compatibility should still work. If it doesn't, then it's something with the decoder/renderer.

I also have a file that has the same HDR format, and it plays fine with MPC-BE + madVR.

**Comment by hyllm** [comment]
playing source is OK... source is OK. but when I extract HDR10+ metadata and use them in encode, the result is

> Format : HEVC
> Format/Info : High Efficiency Video Coding
> Format profile : Main 10@L5.1@High
> **HDR format : SMPTE ST 2094 App 4, Version 1**

The **HDR10+ Profile B compatible** is missing, and **HDR10 compatible** is missing too.

When I encode without HDR10+ metadata, I get correct HDR10 encode.

> Format : HEVC
> Format/Info : High Efficiency Video Coding
> Format profile : Main 10@L5.1@High
> HDR format : SMPTE ST 2094 App 4, Version 1, HDR10 Compatible

So something must be wrong with JSON metadatafile. Other HDR10+ titles are encoding correctly, co no problem with encoder.

**Comment by quietvoid** [comment]
That doesn't look like a regular HDR10 file.
The MediaInfo of a simple HDR10 file would look like this: `SMPTE ST 2086, HDR10 compatible`.
While an HDR10+ file looks like this: `SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

I don't know how you got to the MediaInfo you posted.

**Comment by hyllm** [comment]
it's like you wrote... mixed copy/paste. :)

anyway, with this title, the hdr10+ metadata causing what is in first post. :)

**Comment by quietvoid** [comment]
There is nothing wrong with the metadata file. Parsing the source and encoding works fine.
Parsing the encode file with hdr10plus_parser works fine.
HDR is detected properly on playback.

If your player does not detect HDR, it is not the parser's problem.

**Comment by ValZapod** [comment]
> That doesn't look like a regular HDR10 file.
> The MediaInfo of a simple HDR10 file would look like this: `SMPTE ST 2086, HDR10 compatible`.
> While an HDR10+ file looks like this: `SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`
> 
> I don't know how you got to the MediaInfo you posted.

That may be a bug in Mediainfo. SMPTE ST 2094 App 4, Version 0, HDR10 compatible should be impossible, no?
