### ISSUE TITLE
HDR10+ Profile changed with data parsed with version 0.2.5

### ISSUE THREAD

**Issue by hyllm** [quietvoid/hdr10plus_parser#13]
Metadata extracted with 0.2.5..

Movie: X-Men Dark Phoenix... will upload a sample, if needed...

Source
`HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible`

Encoded with x265 3.2+20
`HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

When using metadata parsed with 0.2.4, everything is OK, and HDR10+ Profile is the same as source.

**Comment by quietvoid** [comment]
I really have no idea what the profiles mean.
The only difference is that 0.2.4 does not keep empty metadata fields in the JSON, so technically there should not be a real difference.
It was the fix for #10

**Comment by quietvoid** [comment]
Closing this as it seems like a non issue and no response.
