### ISSUE TITLE
Refactor MaxScl parsing

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/hdr10plus_parser#16]
The current code is an absolute mess, even though it "works".
There is a lot of unexpected behavior, including but not limited to:

- Differences when AverageRGB is high.
- Differences when TargetedSystemDisplayMaximumLuminance is high (and equal to 8192).
- Differences depending on previously parsed MaxScl values, whether they are zero, low or high.

**Comment by jojo54000** [comment]
Are you talking about version 0.2.7 ?

**Comment by quietvoid** [comment]
This issue is not related to the usage of the parser, only the quality and maintainability of the code.

**Comment by quietvoid** [comment]
I've looked into fixing this but the behavior is still very inconsistent, no matter how the data is read.

**Comment by quietvoid** [comment]
If anyone's interesting in helping debug this, here's some test code that tries to reproduce x265's output.
[hdr10plus_debug.zip](https://github.com/quietvoid/hdr10plus_parser/files/5392149/hdr10plus_debug.zip)

**Comment by quietvoid** [comment]
Traced back to the source in x265:
```
if (bytes >= 2 && !out[bytes - 2] && !out[bytes - 1] && inBytes[i] <= 0x03)
{
    /* inject 0x03 to prevent emulating a start code */
    out[bytes++] = 3;
}
```
