### ISSUE TITLE
A problem with .h265 files

### ISSUE THREAD

**Issue by Summer60** [quietvoid/hdr10plus_parser#17]
I've been trying to extract the frames of .h265 files stored in assets folder but except a few of them, the rest of the files give me totally black frames. I am using this command to extract the frames:

ffmpeg -i ToS-s37.h265 -r 1/1 $filename%03d.bmp

Any solution?

**Comment by quietvoid** [comment]
That's not an issue, the files in the assets folder are mostly 1-3 frames long.
It just so happens the trimmed section of the sample I used are black frames.

The files just act as validation for testing, since they were encoded using different JSON metadata.

**Comment by Summer60** [comment]
Thanks. I understand. Unfortunately except first few ones, rest of them are black. I really liked to see which frames these JSON files corresponds to. 

Can you please explain how you convert a clip to .h265 format? Has the code been uploaded here? I did using ffmpeg but lost dynamic metadata.

**Comment by quietvoid** [comment]
You can look at the `lib.rs` file for the metadata corresponding to each HEVC file.

I used x265 directly. Something like this:
`x265 --hdr10 --dhdr10-info /path/to/metadata.json`

**Comment by Summer60** [comment]
I had no problem with extracting Json files from your sample clips. Your code was working perfectly. However, I would like to not be restricted to these ToS samples. I want to make more myself. That's why I asked how you converted mp4 to h265 and preserved dynamic meta data. I wish the code was working with some other type of video format as well. Apparently, it just works with HEVC.

**Comment by quietvoid** [comment]
This type of question is more appropriate to be asked on Doom9.
You might find some answers in this thread: https://forum.doom9.org/showthread.php?t=175947

Closing this.
