### ISSUE TITLE
Sample JSON metadata link broken

### ISSUE THREAD

**Issue by cdgriffith** [quietvoid/hdr10plus_parser#19]
https://bitbucket.org/multicoreware/x265/downloads/ gives a message: 

"Repository unavailable
Bitbucket no longer supports Mercurial repositories."

I *think* the new link is https://bitbucket.org/multicoreware/x265_git/downloads/ but I am not one of the devs or anyway associated with them.

**Comment by quietvoid** [comment]
Thanks.
