### ISSUE TITLE
invalid input type

### ISSUE THREAD

**Issue by Zeid164** [quietvoid/hdr10plus_parser#23]
on somes files i get : 

hdr10plus_parser.exe t.mkv -o t.json
Invalid input file type.

media info are : 
General
Unique ID                      : 241124782803669710001353165176884576603 (0xB566F1A6F08743B9B796BBD77F62415B)
Complete name                  : E:\t.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 42.1 GiB
Duration                       : 1 h 48 min
Overall bit rate mode          : Variable
Overall bit rate               : 55.7 Mb/s
Encoded date                   : UTC 2017-11-28 14:20:11
Writing application            : mkvmerge v9.4.0 ('Knurl') 64bit
Writing library                : libebml v1.3.4 + libmatroska v1.4.5

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@High
HDR format                     : SMPTE ST 2086, HDR10 compatible
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 1 h 48 min
Bit rate                       : 45.0 Mb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.226
Stream size                    : 34.0 GiB (81%)
Writing library                : ATEME Titan KFE 3.7.3 (4.7.3.1003)
Language                       : English
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : Display P3
Mastering display luminance    : min: 0.0000 cd/m2, max: 1000 cd/m2

Audio #1
ID                             : 2
Format                         : MLP FBA 16-ch
Format/Info                    : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                : Dolby TrueHD with Dolby Atmos
Codec ID                       : A_TRUEHD
Duration                       : 1 h 48 min
Bit rate mode                  : Variable
Bit rate                       : 5 024 kb/s
Maximum bit rate               : 8 466 kb/s
Channel(s)                     : 8 channels
Channel layout                 : L R C LFE Ls Rs Lb Rb
Sampling rate                  : 48.0 kHz
Frame rate                     : 1 200.000 FPS (40 SPF)
Compression mode               : Lossless
Stream size                    : 3.79 GiB (9%)
Language                       : English
Default                        : No
Forced                         : No
Number of dynamic objects      : 13
Bed channel count              : 1 channel
Bed channel configuration      : LFE

Audio #2
ID                             : 3
Format                         : DTS ES XLL
Format/Info                    : Digital Theater Systems
Commercial name                : DTS-HD Master Audio
Codec ID                       : A_DTS
Duration                       : 1 h 48 min
Bit rate mode                  : Variable
Bit rate                       : 4 892 kb/s
Channel(s)                     : 8 channels
Channel layout                 : C L R Ls Rs LFE Lb Rb
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 24 bits
Compression mode               : Lossless
Stream size                    : 3.69 GiB (9%)
Language                       : English
Default                        : No
Forced                         : No

Audio #3
ID                             : 4
Format                         : DTS
Format/Info                    : Digital Theater Systems
Codec ID                       : A_DTS
Duration                       : 1 h 48 min
Bit rate mode                  : Constant
Bit rate                       : 768 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 24 bits
Compression mode               : Lossy
Stream size                    : 594 MiB (1%)
Title                          : VFF
Language                       : French
Default                        : Yes
Forced                         : No

Text #1
ID                             : 5
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 1 h 44 min
Bit rate                       : 11.0 kb/s
Count of elements              : 2766
Stream size                    : 8.23 MiB (0%)
Title                          : Full
Language                       : English
Default                        : No
Forced                         : No

Text #2
ID                             : 6
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 1 h 45 min
Bit rate                       : 9 345 b/s
Count of elements              : 2746
Stream size                    : 7.02 MiB (0%)
Title                          : Full
Language                       : French
Default                        : No
Forced                         : No

Text #3
ID                             : 7
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 1 h 38 min
Bit rate                       : 30 b/s
Count of elements              : 6
Stream size                    : 22.4 KiB (0%)
Title                          : Forced
Language                       : French
Default                        : Yes
Forced                         : Yes

Menu
00:00:00.000                   : en:Chapter 01
00:03:04.726                   : en:Chapter 02
00:05:53.019                   : en:Chapter 03
00:09:30.820                   : en:Chapter 04
00:13:19.089                   : en:Chapter 05
00:16:48.716                   : en:Chapter 06
00:20:12.544                   : en:Chapter 07
00:22:06.408                   : en:Chapter 08
00:27:09.628                   : en:Chapter 09
00:31:58.958                   : en:Chapter 10
00:36:51.709                   : en:Chapter 11
00:41:06.172                   : en:Chapter 12
00:44:45.766                   : en:Chapter 13
00:46:56.605                   : en:Chapter 14
00:50:10.966                   : en:Chapter 15
00:53:18.028                   : en:Chapter 16
00:55:33.038                   : en:Chapter 17
00:59:07.752                   : en:Chapter 18
01:03:05.239                   : en:Chapter 19
01:07:06.439                   : en:Chapter 20
01:09:15.568                   : en:Chapter 21
01:12:29.720                   : en:Chapter 22
01:16:46.393                   : en:Chapter 23
01:20:43.713                   : en:Chapter 24
01:25:53.398                   : en:Chapter 25
01:31:03.791                   : en:Chapter 26
01:34:46.972                   : en:Chapter 27
01:39:52.736                   : en:Chapter 28

**Comment by quietvoid** [comment]
Matroska is not supported currently, use ffmpeg and pipe the output like the README says:
`ffmpeg -i "input.mkv" -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_parser.exe -o metadata.json -`
