### ISSUE TITLE
mass parsing

### ISSUE THREAD

**Issue by Zeid164** [quietvoid/hdr10plus_parser#24]
it would be great if we could : 

hdr10plus_parser.exe t.mkv
=> and it generate itsel t_parsed.json if data found

and even better : 
hdr10plus_parser.exe *.mkv
=> and it do the job for all files

**Comment by quietvoid** [comment]
I don't see a good use case for glob patterns, the same behavior can easily be done with a simple bash/powershell script.
This would also only work for raw HEVC files, as Matroska isn't supported as input and ffmpeg is required.

**Comment by Zeid164** [comment]
yes you're probably right
i will write a powershell script
