### ISSUE TITLE
Regression in version 0.3.0

### ISSUE THREAD

**Issue by boulderdash09** [quietvoid/hdr10plus_parser#26]
When I want to extract a metadata json file from my hevc with hdr10plus_parser 0.3.0, I have this error message at the end (and no json file) :

thread 'main' panicked at 'called Result::unwrap() on an Err value: Parse("not enough data: expected 12 bits got 2 bits")', src/hdr10plus/parser.rs:233:71
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

It works fine if I use version 0.2.8 or version 0.2.9 on the same hevc (no error message) and I have my json file.

**Comment by quietvoid** [comment]
This has been fixed in master but I haven't created a release, I'll make a hotfix release I guess.

**Comment by boulderdash09** [comment]
Yes it works with this new version !!

Thanks a lot for all your work, it's really impressive.
