### ISSUE TITLE
Error parsing a UHD file

### ISSUE THREAD

**Issue by jlw4049** [quietvoid/hdr10plus_parser#27]
[34mReading parsed dynamic metadata... [0mthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse("not enough data: expected 12 bits got 2 bits")', src/hdr10plus/parser.rs:233:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by quietvoid** [comment]
Are you using the latest version? This shouldn't happen with 0.3.1.

**Comment by jlw4049** [comment]
I'll double check that now

**Comment by jlw4049** [comment]
You was right, closing this issue. My bad!
