### ISSUE TITLE
Build trouble on Mac OS

### ISSUE THREAD

**Issue by tinskip** [quietvoid/hdr10plus_parser#28]
I am trying to build your project on Mac OS.  I have not built a Rust project before, but have installed rustc 1.48.0 using rustup, and tried to cargo build. I get errors on one of the dependencies, deku_derive v0.8.0:

error: cannot construct `darling::ast::Fields<_>` with struct literal syntax due to inaccessible fields
  --> /Users/tinskip/.cargo/registry/src/github.com-1ecc6299db9ec823/deku_derive-0.8.0/src/lib.rs:46:60
   |
46 |             ast::Data::Struct(fields) => ast::Data::Struct(ast::Fields {
   |

I have tried the newest version of the deku_derive dependency, 0.9.1 as well, but no luck.  Online searches have turned up nothing.  I know this is not necessarily your bug, but it impacts your project, and was wondering whether someone might know how to fix or work around the problem.

Thanks!

**Comment by quietvoid** [comment]
Seems to be related to https://github.com/sharksforarms/deku/pull/148.

**Comment by quietvoid** [comment]
Should be fixed, I'm generating executables to update the 0.3.1 release.
