### ISSUE TITLE
panicked at 'index out of bounds

### ISSUE THREAD

**Issue by cdgriffith** [quietvoid/hdr10plus_parser#29]
Using latest `0.3.1`  on Windows 10 with ffmpeg `N-100471-gbff6fbead8` (built in last month)

Command: 
```
ffmpeg -y -i video.mkv -map 0:v -loglevel panic -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_parser -o metadata.json -
```

Error: 
```
←[34mParsing HEVC file for dynamic metadata... ←[0m
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src\hdr10plus\parser.rs:44:20
stack backtrace:
   0:     0x7ff7e6e91cb9 - <unknown>
   1:     0x7ff7e6ea799b - <unknown>
   2:     0x7ff7e6e8e788 - <unknown>
   3:     0x7ff7e6e948d4 - <unknown>
   4:     0x7ff7e6e944b8 - <unknown>
   5:     0x7ff7e6e9518f - <unknown>
   6:     0x7ff7e6e94cf5 - <unknown>
   7:     0x7ff7e6e9259f - <unknown>
   8:     0x7ff7e6e94ca9 - <unknown>
   9:     0x7ff7e6ea56f0 - <unknown>
  10:     0x7ff7e6ea56b7 - <unknown>
  11:     0x7ff7e6d75b98 - <unknown>
  12:     0x7ff7e6d65769 - <unknown>
  13:     0x7ff7e6d622a6 - <unknown>
  14:     0x7ff7e6d776ac - <unknown>
  15:     0x7ff7e6e95393 - <unknown>
  16:     0x7ff7e6d66087 - <unknown>
  17:     0x7ff7e6eaef44 - <unknown>
  18:     0x7ff9a18c7034 - BaseThreadInitThunk
  19:     0x7ff9a259d0d1 - RtlUserThreadStart
  ```
  
  
Have had this issue on two separate videos, both with similar HDR profiles, may be due to also having Dolby Vision? 

```
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
```

Thanks for this great utility, I hope to incorporate it into [FastFlix](https://github.com/cdgriffith/FastFlix) soon 😄 

Edit: I did also try with `--force-single-profile` and there is no change.

**Comment by quietvoid** [comment]
I'm not too sure how that happens. Dolby Vision should not make a difference.
Maybe if the input file is very small?

I've improved the condition to avoid the issue in cfd5db9bfdfb6cce11edb5b9a48be129e763aa6a

You can try the new binary once it's done building.

**Comment by cdgriffith** [comment]
That does fix the out of bounds issue! 

These are both large files that the cannot parse NAL units when converting. May be a new style of hdr10+? 

If you want to talk about it more off github issues, my email is chris@cdgriffith.com

**Comment by quietvoid** [comment]
Can you share a sample or the title? The format of the metadata does not change, it is frozen in spec as ITU T35 metadata.

**Comment by cdgriffith** [comment]
Well, that's weird. Doing a copy of the video via FFmpeg seems to fix the new file  (tried cutting it down to a second to make it easier) but then it worked fine. 

If you can email me or discord .Chris.#5196 can talk more specifics.

**Comment by quietvoid** [comment]
Don't know. Closing this.
