### ISSUE TITLE
feature request: pipe input

### ISSUE THREAD

**Issue by Selur** [quietvoid/hdr10plus_parser#3]
It would be helpful if one could use something like:
```
ffmpeg -i "<path to file>" -vcodec copy -an -sn -vbsf h265_mp4toannexb - | hdr10plus_parser.exe -
```
to directly feed hdr10plus_parser with the raw video stream without having to extract the raw video first into a temporary file.

**Comment by quietvoid** [comment]
I'll look into this, definitely would save time.
