### ISSUE TITLE
Error parsing file

### ISSUE THREAD

**Issue by stillempty** [quietvoid/hdr10plus_parser#34]
[34mReading parsed dynamic metadata... [0m[32mDone.[0m
[34mReordering metadata... [0mthread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\hdr10plus\parser.rs:341:18
stack backtrace:
   0:     0x7ff74e62217f - <unknown>
   1:     0x7ff74e63752a - <unknown>
   2:     0x7ff74e61f4b8 - <unknown>
   3:     0x7ff74e624bc6 - <unknown>
   4:     0x7ff74e6246a9 - <unknown>
   5:     0x7ff74e625225 - <unknown>
   6:     0x7ff74e624de3 - <unknown>
   7:     0x7ff74e622acf - <unknown>
   8:     0x7ff74e624d69 - <unknown>
   9:     0x7ff74e643ef0 - <unknown>
  10:     0x7ff74e643e3c - <unknown>
  11:     0x7ff74e4f9197 - <unknown>
  12:     0x7ff74e506883 - <unknown>
  13:     0x7ff74e4f8691 - <unknown>
  14:     0x7ff74e4f1fd6 - <unknown>
  15:     0x7ff74e4f244c - <unknown>
  16:     0x7ff74e62563a - <unknown>
  17:     0x7ff74e4f90b7 - <unknown>
  18:     0x7ff74e63e080 - <unknown>
  19:     0x7ffab4297974 - BaseThreadInitThunk
  20:     0x7ffab6b6a2f1 - RtlUserThreadStart

If there is any other data you need please let me know.

**Comment by quietvoid** [comment]
A sample to reproduce is necesary.

**Comment by stillempty** [comment]
I am fairly new to github.  The video file is about 2.8 GB, if you need the whole file, how is the best way to get it to you?

**Comment by quietvoid** [comment]
I'm not sure, maybe MEGA?

**Comment by stillempty** [comment]
https://drive.google.com/file/d/1IxQ6RiyLG4UfoduBVOUQdL26iqAbi3gg/view?usp=sharing

Can you remove the link once you have the file please or let me know so I can delete it.

**Comment by quietvoid** [comment]
I have downloaded the file, thanks.

**Comment by quietvoid** [comment]
I had no problem parsing the file with version 0.5.0.
What exact command line are you getting the error with?

**Comment by stillempty** [comment]
ffmpeg.exe -i S01E07.mkv -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_parser -o metadata.json -

The other 7 episodes processed properly

**Comment by quietvoid** [comment]
Huh this is kinda weird, it doesn't always fail for me.

**Comment by stillempty** [comment]
I can test the metadata file you were able to extract if you like.  So reading your comment it did fail for you also?

**Comment by quietvoid** [comment]
Yes it fails but not always.

**Comment by quietvoid** [comment]
This was interesting to fix. The problem only happened for stdin input (ffmpeg piping).

Since HDR10+ metadata is contained in SEI prefix NALs, the metadata was decoded before the actual frame slices.
However because using stdin is unpredictable, sometimes the read data would end up decoding all the metadata, but skipping the very last slice, which is necessary for presentation order info.

Now the parsing should not skip any data.
Thanks!
