### ISSUE TITLE
feature requires: option to set output filename/path

### ISSUE THREAD

**Issue by Selur** [quietvoid/hdr10plus_parser#4]
Using:
`ffmpeg -i "E:\Output\HDR-10+.mp4" -vcodec copy -an -sn -vbsf h265_mp4toannexb -f rawvideo - | hdr10plus_parser.exe -`
the output is created next to the hdr10plus_parser.exe would be nice to specify where the output files should be created and what they are named to avoid collisions  when extracting mutiple files. (with pipe input, output is named 'pipe-meta.json')

as a side note an additional option to dis-/enable the log would be nice too. :)

**Comment by quietvoid** [comment]
I gotta improve the whole input/output system. It's all very lazily inplemented.
The reason #5 fails because it's expecting the first parameter to be the input.

**Comment by quietvoid** [comment]
I've used clap-rs to handle the CLI arguments easily: https://github.com/clap-rs/clap

The tool now runs with either and more of these options:
`hdr10plus_parser.exe ".\input.mkv" ".\output.json"`
`hdr10plus_parser.exe -i ".\input.mkv" -o ".\output.json"`
`ffmpeg .. - | hdr10plus_parser.exe - -o ".\output.json"

If the output is omitted, then default is to only verify the metadata.

And flags like --verify can be set anywhere now :)
