### ISSUE TITLE
pipe input also for verify

### ISSUE THREAD

**Issue by Selur** [quietvoid/hdr10plus_parser#5]
`ffmpeg -i "E:\Output\HDR-10+.mp4" -vcodec copy -an -sn -vbsf hevc_mp4toannexb -f rawvideo - | hdr10plus_parser.exe -`
works fine, would be nice if:
`ffmpeg -i "E:\Output\HDR-10+.mp4" -vcodec copy -an -sn -vbsf hevc_mp4toannexb -f rawvideo - | hdr10plus_parser.exe --verify -`
would also work, atm. I get
```
File path not found.
```

**Comment by Selur** [comment]
Ah okay, tested:
`ffmpeg -i "E:\Output\HDR-10+.mp4" -vcodec copy -an -sn -vbsf hevc_mp4toannexb -f rawvideo - | hdr10plus_parser.exe - --verify`
does seem to do the trick. :)

**Comment by quietvoid** [comment]
Fixed in e436f96fec0abc28433f9f0eb46bbfb99e954e0f, release 0.2.3 available.
