### ISSUE TITLE
when I cargo run，I meet this error，can you help me？

### ISSUE THREAD

**Issue by MIS-CAT** [quietvoid/hdr10plus_parser#8]
thread 'main' panicked at 'Non-unique argument name: INPUT is already in use', C
:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.32.
0\src\app\parser.rs:174:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\debug\hdr10plus_parser.exe` (ex
it code: 101)

**Comment by quietvoid** [comment]
I'm not sure why but running `cargo run` causes the error only on dev target (unoptimized).
Leaving a single INPUT arg for clap-rs breaks the functionality so I'd rather leave it like that until I can look more into why it's breaking.

The tool runs optimally with as a release/optimized binary, so please try running `cargo run --release ..`

**Comment by MIS-CAT** [comment]
I‘m so sorry, it's my first time to use rust, I have many problems.

I used cargo run --release .. and then meet the new problem

 Finished release [optimized] target(s) in 21.56s
     Running `target/release/hdr10plus_parser ..`
File path not found.

Then, I tried cargo run --release, there is another error.

chelsea@chelsea-System-Product-Name:~/test/hdr10plus_parser-master$ cargo run --release
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/hdr10plus_parser`
error: The following required arguments were not provided:
    <INPUT>

USAGE:
    hdr10plus_parser [FLAGS] [OPTIONS] <INPUT> [OUTPUT]

For more information try --help

**Comment by quietvoid** [comment]
The `cargo run --release ..` was an example. You need an actual input file.
For the second error, it should say missing INPUT argument so not sure.

Try doing `cargo run --release assets/ToS-s1.h265`

**Comment by MIS-CAT** [comment]
OK, I got it. I run  `hdr10plus_parser.exe out.hevc` , It is built successfully, and print the following statement. I want to know, where I can find the JSON file the dynamic metadata existed, or how to get the JSON file.

Parsing HEVC file for dynamic metadata...
[00:00:00] ██████████████████████████████████
██████████████████████████ 100%
Dynamic HDR10+ metadata detected.

Thank you very much , you are so nice.

**Comment by MIS-CAT** [comment]
I got it! I can parser the dynamic metadata from hevc file now. Thank you very much!!

**Comment by quietvoid** [comment]
Good to hear.
